"""cascase delete tasks with board

Revision ID: d5e3459ee511
Revises: 60f29fef6aed
Create Date: 2026-09-27 08:00:47.728602

"""
import sqlmodel.sql.sqltypes
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e3459ee511'
down_revision: Union[str, Sequence[str], None] = '60f29fef6aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_board_id'), 'task', ['board_id'], unique=False)
    op.drop_constraint(op.f('task_board_id_fkey'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_board_id_board'), 'task', 'board', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_board_id_board'), 'task', type_='foreignkey')
    op.create_foreign_key(op.f('task_board_id_fkey'), 'task', 'board', ['board_id'], ['id'])
    op.drop_index(op.f('ix_task_board_id'), table_name='task')
    # ### end Alembic commands ###
